### ISSUE TITLE
There is no "Adopt" button

### ISSUE THREAD

**Issue by 5ong** [truffle-box/pet-shop-box#11]
Hi,
Everything works great but the webpage shows only "Success" buttons (see attached). Please point me to the right direction.
Thanks,
-5ong
![sshot1](https://user-images.githubusercontent.com/23251479/33353275-e9e2060e-d461-11e7-8359-e4bb0062cbfe.PNG)

**Comment by BeFiveINFO** [comment]
hi, I am not sure if this works for you.

I have just had the same problem as yours.

I stopped the "lite-server" and I tried the following command in the terminal:

```
truffle migrate
```

Then I restarted the "lite-server" with "npm run dev".

Good luck.
