### ISSUE TITLE
No response clicking "adopt" button

### ISSUE THREAD

**Issue by yuliji** [truffle-box/pet-shop-box#15]
I am following the tutorial here: http://truffleframework.com/tutorials/pet-shop

At first, every step is successful, but when I finally test the pet shop in chrome, there is no response when I click the "adopt" button.

Truffle v4.0.3 (core: 4.0.3)
Solidity v0.4.18 (solc-js)

Chrome Version 62.0.3202.94 (Official Build) (64-bit)
MetaMask 3.13.2
Ganache 1.0.1
mac os 10.12.6

**Comment by droidrockgirl** [comment]
I'm having the same issue

**Comment by zerostatic** [comment]
Make sure you are running `truffle develop` in another terminal

**Comment by yangyao** [comment]
I'm having the same issue I use Ganache.

**Comment by Coolpix** [comment]
There's a problem with the contract.

We have two methods:

// Adopting a pet
    function adopt(uint petId) public view returns (uint) {
        require(petId >= 0 && petId <= 15);
        adopters[petId] = msg.sender;
        return petId;
    }

    // Retrieving the adopters
    function getAdopters() public returns (address[16]) {
        return adopters;
    }

We cannot set the view in a method that modify the contract storage, we should use view only in method that get data from contract, so there's a mistake.

Change the methods to this:

// Adopting a pet
    function adopt(uint petId) public returns (uint) {
        require(petId >= 0 && petId <= 15);
        adopters[petId] = msg.sender;
        return petId;
    }

    // Retrieving the adopters
    function getAdopters() public view returns (address[16]) {
        return adopters;
    }

**Comment by takahirosawamura** [comment]
I'm having the same issue....

**Comment by RC90** [comment]
Hey,
I had the same error. For me the solution was to check all the )  , }  and ;  statements in app.js 
Heres my working file:
[app.txt](https://github.com/truffle-box/pet-shop-box/files/1629336/app.txt)

**Comment by RC90** [comment]
[app.txt](https://github.com/truffle-box/pet-shop-box/files/1629495/app.txt)
I had the same problem. Helped me a lot to check for missing or wrong ) }  ;  statements.
Here's my app.js where the button works.

**Comment by 0pay** [comment]
I have followed all the pet -shop tutorial.
Instead to use Ganache I have used "truffle develop".
In the web3 code I inserted
1) App.web3Provider = new web3.providers.HttpProvider('http://127.0.0.1:9545');
2) In MetaMask, I entered int the "New RPC URL" field  the address "http://127.0.0.1:9545"
The adopt button doesn't work.
Would you please help me.
thanks

**Comment by yyyfor** [comment]
same issue here. Everytime i click adopt, button become success. Ganache get no response.

**Comment by sonivivek** [comment]
below change worked for me......single quote to double quote

before
  bindEvents: function() {
    $(document).on('click', '.btn-adopt', App.handleAdopt);
After 

  bindEvents: function() {
    $(document).on("click", '.btn-adopt', App.handleAdopt);

**Comment by luckyuho** [comment]
> [app.txt](https://github.com/truffle-box/pet-shop-box/files/1629495/app.txt) I had the same problem. Helped me a lot to check for missing or wrong ) } ; statements. Here's my app.js where the button works.

This is the result of referring to the official website and the above documents
Reference for anyone facing the same problem in 2022 : )
[app.txt](https://github.com/truffle-box/pet-shop-box/files/8104221/app.txt)
