### ISSUE TITLE
re: issue with first compile

### ISSUE THREAD

**Issue by suspectzed** [truffle-box/pet-shop-box#19]
Not sure what the issue is.... 

truffle compile

Compiling ./contracts/Adoption.sol...
Compiling ./contracts/Migrations.sol...

Compilation warnings encountered:

/home/ubuntu/eth_projects/PetShop/contracts/Migrations.sol:11:3: Warning: No visibility specified. Defaulting to "public".
  function Migrations() {
  ^
Spanning multiple lines.
,/home/ubuntu/eth_projects/PetShop/contracts/Migrations.sol:15:3: Warning: No visibility specified. Defaulting to "public".
  function setCompleted(uint completed) restricted {
  ^
Spanning multiple lines.
,/home/ubuntu/eth_projects/PetShop/contracts/Migrations.sol:19:3: Warning: No visibility specified. Defaulting to "public".
  function upgrade(address new_address) restricted {
  ^
Spanning multiple lines.

/home/ubuntu/eth_projects/PetShop/contracts/Migrations.sol:11:3: Warning: No visibility specified. Defaulting to "public".
  function Migrations() {
  ^
Spanning multiple lines.
,/home/ubuntu/eth_projects/PetShop/contracts/Migrations.sol:15:3: Warning: No visibility specified. Defaulting to "public".
  function setCompleted(uint completed) restricted {
  ^
Spanning multiple lines.
,/home/ubuntu/eth_projects/PetShop/contracts/Migrations.sol:19:3: Warning: No visibility specified. Defaulting to "public".
  function upgrade(address new_address) restricted {
  ^
Spanning multiple lines.
,/home/ubuntu/eth_projects/PetShop/contracts/Adoption.sol:8:11: DeclarationError: Undeclared identifier.
  require(petID >= 0 && petID <=15) ;
          ^---^

Compilation failed.  See above.
-------------------------------------------------------------------

Here is my system:  Ubuntu 16.04
sudo npm -v
5.6.0

sudo nodejs -v
v9.3.0

echo $PATH
/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/eth_projects/PetShop

pwd
/home/ubuntu/eth_projects/PetShop/

more /contracts/Adoption.sol
pragma solidity ^0.4.17;

contract Adoption {
address[16] public adopters;

// Adopting a pet
function adopt(uint petId) public returns (uint) {
  require(petID >= 0 && petID <=15) ;

  adopters[petID] = msg.sender;

  return petId;
  }

// Retrieving the adopters
function getAdopters() public view returns (address[16]) {
  return adopters;
  }

}

**Comment by jinwyp** [comment]
add “public” to 3 function below  in file contracts/Migrations.sol



```

  function Migrations() public{
    owner = msg.sender;
  }

  function setCompleted(uint completed) public restricted {
    last_completed_migration = completed;
  }

  function upgrade(address new_address) public restricted {
    Migrations upgraded = Migrations(new_address);
    upgraded.setCompleted(last_completed_migration);
  }
```

**Comment by swellander** [comment]
I have a similar problem with my first attempt at compiling.

> pet-shop-box-master/contracts/Adoption.sol: ParsedContract.sol:8:1: ParserError: Expected pragma, import directive or contract/interface/library definition.
function adopt(uint petId) public returns (uint) {
^
Compilation failed. See above.




Adoption.sol
---------------
`pragma solidity ^0.4.17;

contract Adoption {
  address[16] public adopters;
}

// Adopting a pet
function adopt(uint petId) public returns (uint) {
  require(petId >= 0 && petId <= 15);

  adopters[petId] = msg.sender;

  return petId;
}

// Retrieving the adopters
function getAdopters() public view returns (address[16]) {
  return adopters;
}
`
____________
I tried adding "public" to Migrations.sol with no luck. Any ideas?

**Comment by suspectzed** [comment]
I see two grammatical errors:
/* remove the character " ` " pragma; should read as follows  */
pragma solidity ^0.4.17;

contract Adoption {
address[16] public adopters;
// you close bracket here "}" but should remove this close out of contract Adoption and place at the end

// Adopting a pet
function adopt(uint petId) public returns (uint) {
  require(petid >= 0 && petId <=15);

  adopters[petId] = msg.sender;

  return petId;
  }

// Retrieving the adopters
function getAdopters() public view returns (address[16]) {
  return adopters;
  }


}
// above bracket closes the contract Adoption

**Comment by swellander** [comment]
Thanks!

**Comment by Taro0329** [comment]
Hi Peeps,

I have similar problem.

after I wrote following codes.

`pragma solidity ^0.4.17;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Adoption.sol";

contract TestAdoption {
  Adoption adoption = Adoption(DeployedAddresses.Adoption());

  function testUserCanAdoptPet() public {
      uint returnedId = adoption.adopt(8);

      uint expected = 8;

      Assert.equal(returnedId, expected, "Adoption of pet ID 8 should be recorded.");
  }

  function testGetAdopterAddressByPetId() public {
      address expected = this;

      address adopter = adoption.adopters(8);

      Assert.equal(adopter, expected, "Owner of pet ID 8 should be recorded.");
  }
}`

and back in the terminal, run the tests, terminal showed this error:
-----------------
C:\Users\Taro\pet-shop-tutorial>truffle.cmd test
Using network 'development'.

Compiling .\contracts\Adoption.sol...
Compiling .\test\TestAdoption.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

/C/Users/Taro/pet-shop-tutorial/test/TestAdoption.sol:11:25: TypeError: Member "adopt" not found or not visible after argument-dependent lookup in contract Adoption
      uint returnedId = adoption.adopt(8);
                        ^------------^
Compilation failed. See above.
-----------------
can anyone please let me know how to solve this issue?

Thank you

**Comment by ddlandim** [comment]
**about this error:** 
TypeError: Member "getAdopters" not found or not visible after argument-dependent lookup in contract Adoption.
          address[16] memory adopters = adoption.getAdopters();
                                        ^------------------^

I was looking carefully at the error when compiling the test, indicating that the function was not "visible"
acquire this getter function and it was there ... however the type of feedback caught my attention, it was not the same as the test.
so I deleted and call truffle test again, the "see" which generated a compilation warning:
  Warning: Function state mutability can be restricted to view
         function getAdopters () public returns (address [16] memory) {
  ^ (Relevant source part starts here and spans across multiple lines).

But it worked !!!

SO...
Remove "view" return type in the function getAdopters() Adoption.sol : 
// Retrieving the adopters
	function getAdopters() public **view** returns (address[16] memory) {
	  return adopters;
	}

to

// Retrieving the adopters
	function getAdopters() public  returns (address[16] memory) {
	  return adopters;
	}
