### ISSUE TITLE
Meta Mask change on 2nd November - Petshop tutorial web page no longer interacts with metamask!!!!

### ISSUE THREAD

**Issue by dubirl** [truffle-box/pet-shop-box#33]
Metamask have implemented a change which no longer exposes account by default - which mean whilst the tutorial still works - the interaction with metamask no longer occurs -

I began playing with this early this year and was good introduction on how the various pieces hang together. I am using it again as part of a demo for college but need some help
Details of the reason they have stopped metamask interacting by default are here:

https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

It mention that the following code should be added but I am not sure where - should it be in the app.js file?

The following code shows a new way to start up a dapp that can be used today in both legacy and modern dapp browsers:

```js
window.addEventListener('load', async () => {
    // Modern dapp browsers...
    if (window.ethereum) {
        window.web3 = new Web3(ethereum);
        try {
            // Request account access if needed
            await ethereum.enable();
            // Acccounts now exposed
            web3.eth.sendTransaction({/* ... */});
        } catch (error) {
            // User denied account access...
        }
    }
    // Legacy dapp browsers...
    else if (window.web3) {
        window.web3 = new Web3(web3.currentProvider);
        // Acccounts always exposed
        web3.eth.sendTransaction({/* ... */});
    }
    // Non-dapp browsers...
    else {
        console.log('Non-Ethereum browser detected. You should consider trying MetaMask!');
    }
});
```

**Comment by dennymrh** [comment]
Did you fix this?

**Comment by adrianmcli** [comment]
@dennymrh Yes we did, from what I remember. Did something break again? If so, feel free to make a new issue.

**Comment by modianar** [comment]
@dubirl yes u can write it in App.js file

**Comment by dennymrh** [comment]
I've just added that piece of code mentioned by @dubirl into App.js. Now it connects to the wallet, but every Adopt button turns into Success without me doing anything.

**Comment by adrianmcli** [comment]
@dennymrh Can you upload a reproduction repo onto GitHub?

**Comment by dennymrh** [comment]
@adrianmcli sent you an email

**Comment by adrianmcli** [comment]
@dennymrh Can you make a new issue and post the link to the reproduction repo there? Feel free to tag me in the new issue as well.
