### ISSUE TITLE
Contract is not compiling / migrating

### ISSUE THREAD

**Issue by julkr** [truffle-box/pet-shop-box#41]
I'm following all the steps in the tutorial, but when I'm compiling and migrating the contract nothing happens - no errors, no status messages.

Last year I did this tutorial and all was fine. Could you please recheck all files. 
Maybe it is anyhow connected with the latest updates and solidity 0.5.0.

**Comment by coreyshirk** [comment]
@julkr what version is your truffle? I was getting the same behavior on truffle@5.0.6 so I rolled it back to version 5.0.5 and everything is working.

**Comment by julkr** [comment]
@coreyshirk I had truffle@5.0.6... So I uninstalled it and was trying to install 5.0.5, but got some problems: it looked like it was downloaded, but when I checked truffle's version, there was nothing :(
![screenshot 2019-03-03 at 22 55 17](https://user-images.githubusercontent.com/30115526/53702476-ad9dbd80-3e07-11e9-9d12-1ef60801c40f.png)

So I tried to return to 5.0.6, but now I have problems with installation with keccak:
![screenshot 2019-03-03 at 22 58 26](https://user-images.githubusercontent.com/30115526/53702503-f9506700-3e07-11e9-90d4-77020a68088f.png)

So now I really don't know where to start...

**Comment by coreyshirk** [comment]
@julkr you need to do`npm install truffle@5.0.5 -g`, then you should be able to use the `truffle` command in your first screenshot.

**Comment by modianar** [comment]
![screenshot from 2019-03-06 12-19-04](https://user-images.githubusercontent.com/48201775/53861474-574c9c80-400a-11e9-8cf2-aa5e1b96fb6a.png)


There is no output after compile.What steps should i follow so that compile take place.

**Comment by modianar** [comment]
> ![screenshot from 2019-03-06 12-19-04](https://user-images.githubusercontent.com/48201775/53861474-574c9c80-400a-11e9-8cf2-aa5e1b96fb6a.png)
> 
> There is no output after compile.What steps should i follow so that compile take place.

truffle version
Truffle v5.0.5 (core: 5.0.5)
Solidity v0.5.0 (solc-js)
Node v8.15.0
