### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by RaynHarr** [truffle-box/pet-shop-box#43]
Truffle install seems to work just fine, but the unboxing command is not responding, any ideas?
![Screen Shot 2019-03-28 at 11 23 52 AM](https://user-images.githubusercontent.com/39592448/55170258-9cb54300-514c-11e9-9379-6fc362498cb6.png)

**Comment by modianar** [comment]
Truffle v5.0.7 (core: 5.0.7)
Solidity v0.5.0 (solc-js)
Node v8.15.0
Try out with this Latest Versions

**Comment by marwa-code** [comment]
truffle unbox pet-shop
truffle: command not found 
i face these error when i write these command
