### ISSUE TITLE
Buttons automatically show "success" once Metamask loads

### ISSUE THREAD

**Issue by Nicholasw22** [truffle-box/pet-shop-box#44]
After the app connects to Metamask all of the buttons turn to say "success" even though I haven't clicked on them.

Using Chrome, metamask, apple.

**Comment by modianar** [comment]
Can You please Provide  With the screen Shot So that it can be explain well

**Comment by Nicholasw22** [comment]
Nevermind - I was able to resolve this. Re-worked the tutorial from the beginning. Must have been a typo somewhere along the way. My apologies.
