### ISSUE TITLE
How can we add/delete number of dogs without hard coding done in json file ?

### ISSUE THREAD

**Issue by Lakshmikittur** [truffle-box/pet-shop-box#45]
At present the number of dogs displayed is fixed i.e 11 dogs. What if we want to increase or decrease this number? 

How can we add/delete number of dogs without hard coding done in json file ?

**Comment by modianar** [comment]
1)If you want to add some more pet dogs and delete some more pet dogs  then go to src/pets.json file

**Comment by modianar** [comment]
{
    "id": 12,
    "name": "Frieda",
    "picture": "images/scottish-terrier.jpeg",
    "age": 3,
    "breed": "Scottish Terrier",
    "location": "Lisco, Alabama"
  }

Add like this in pet.json File.....

**Comment by Lakshmikittur** [comment]
Can we create another web page to do so ? Rather than writing directly in pet.json file?

 How can we fill this json file through a web page? Which language can be used?

**Comment by modianar** [comment]
No that cant be possible if you only enter input from html files then only data will be stored in json file.
Input data you send from the html file then u can write it in the json file. You can use Node js for that
use strict';

               const fs = require('fs');
                let data = JSON.stringify(student);  
               fs.writeFileSync('file.json', data, finished);
                function finished(err)
                {
                    console.log('success');
                }

**Comment by modianar** [comment]
You Can use this link for your reference.
https://www.quora.com/How-do-I-save-the-form-input-values-to-an-external-JSON-file-using-JavaScript-or-jQuery

**Comment by Lakshmikittur** [comment]
Ok thank you so much for the help . I will try
