### ISSUE TITLE
Price by adoption

### ISSUE THREAD

**Issue by enrutador** [truffle-box/pet-shop-box#47]
Thanks for your job. It helps a lot to understand the operation of truffle.
In my case I am tested in a private network of quorum. I would like to know how instead of "adopt" I can pay?

For example, I want buy Frieda to cost 3 ethers, and when I adopt it, I can take it from my account to enter it into the seller's account.
Is there an example payable of this style?
Thank you

**Comment by enrutador** [comment]
In case you can help someone:
I do a llitle simulation of a discount of a price with metamask  on a Quorum blockchain adding to the function Handling the adopt()  on file  app.js 

```
        web3.eth.sendTransaction(
            {from:account,
            to: "0x37bbd76d5ae68393170eb61600a0b40eb3ac0470", //The 
            //value: "1000000000000000000",
            value: value,
            gasPrice:'0',
            gas: '2000000',
            data: "Thanks"
                }, function(err, transactionHash) {
          if (!err)
            console.log(transactionHash + " success");
            return adoptionInstance.adopt(petId, {from: account});

        });
        console.log(account);
        console.log(value);

```

This run ok ¡¡ , but i dont like, i will like to add a funtion on the contract Adaption.sol type:

function sendCoin(address receiver, uint amount) public payable returns(bool sufficient) {
 if (balances[msg.sender] < amount) return false;
  balances[msg.sender] -= amount;
  balances[receiver] += amount;
  emit Transfer(msg.sender, receiver, amount);
  emit log_string("Hello World!");
 return true;
}

And call it from the app.js But dont run ;-)

**Comment by modianar** [comment]
Hello Can you please tell exactly where the error is showing.

**Comment by modianar** [comment]
Try to write like this...

or you can refer to this link might it will help you out.
https://gitter.im/ConsenSys/truffle/archives/2018/06/05


event Transfer(address indexed _from, address indexed _to, uint256 _value);

constructor(MetaCoin) public {
    balances[tx.origin] = 10000;
}

function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
    if (balances[msg.sender] < amount) return false;
    balances[msg.sender] -= amount;
    balances[receiver] += amount;
    emit Transfer(msg.sender, receiver, amount);
    return true;
}

function getBalanceInEth(address addr) public view returns(uint){
    return ConvertLib.convert(getBalance(addr),2);
}

function getBalance(address addr) public view returns(uint) {
 return balances[addr];
}
