### ISSUE TITLE
Adopt button issue

### ISSUE THREAD

**Issue by AleksiusK** [truffle-box/pet-shop-box#59]
So I have been trying to get the app to work for a while now, but keep running into an issue when I push the adopt button. The logs show that the contract file adoption.json is not found. The error messages from browser console are below. I solved the errors by moving my contracts folder from build/contracts directly to src and then specified the path to the adoption.json file. Any idea why this is happening? I guess that even though the fix works, this really is not the way it's supposed to work, as the example file did not need to specify any location specifications. I'm working with rinkeby, and metamask connects properly and everything seems to work as it should.

![image](https://user-images.githubusercontent.com/79456654/115958389-fcd76880-a50f-11eb-9b21-14a27fb303f8.png)

Any advice is appreciated! Thanks in advance.

**Comment by tearsofphoenix** [comment]
@AleksiusK you need to add missing files according to the tutorial: https://www.trufflesuite.com/tutorial of pet-shop.

**Comment by Nitishg1223** [comment]
You have to enable the metamask access for the localhost. You can do it by window.ethereum.enable() then only the getAccounts function will work.
