### ISSUE TITLE
Update Bootstrap and change jquery to modern JS

### ISSUE THREAD

**Issue by pinakipb2** [truffle-box/pet-shop-box#63]
update index.html and CSS to get the latest look and feel and update the app.js jquery to modern JS.

**Comment by pinakipb2** [comment]
I would like to work on this.

**Comment by pinakipb2** [comment]
@DiscRiskandBisque Can I get ahead with the updates?

**Comment by kevinbluer** [comment]
hey @pinakipb2, thanks so much for reaching out re this...totally onboard with an update! only question i have before you kick things off is when you say "modern JS" are you implying using a different framework (e.g. React, Vue, Svelte) or something else (e.g. tidying up the current approach, vanilla js, etc)?

**Comment by pinakipb2** [comment]
@kevinbluer Thank You, Sir, for replying. By "modern JS" I mean replacing jquery with vanilla JS.

**Comment by pinakipb2** [comment]
@kevinbluer @DiscRiskandBisque @CruzMolina I also want to update its solution " [https://github.com/trufflesuite/pet-shop-tutorial](https://github.com/trufflesuite/pet-shop-tutorial) ". Please guide me to update the solution.

**Comment by pinakipb2** [comment]
@kevinbluer @DiscRiskandBisque Please have a look at this PR.
