### ISSUE TITLE
Assert.sol and DeployedAddresses.sol files are not found

### ISSUE THREAD

**Issue by SMSGermany** [truffle-box/pet-shop-box#7]
Hi, I am following the pet shop tutorial as mentioned there. But when i am trying to run test then it shows me the following errors! And I can not run the test properly. Any suggestion??

`
c:/trufflePet/truffleDemo/test/TestAdoption.sol:3:1: ParserError: Source "truffle/Assert.sol" not found: File not supplied initially.
import "truffle/Assert.sol";
^--------------------------^
`

`c:/trufflePet/truffleDemo/test/TestAdoption.sol:4:1: ParserError: Source "truffle/DeployedAddresses.sol" not found: File not supplied initially.
import "truffle/DeployedAddresses.sol";
^-------------------------------------^
`

**Comment by NessDan** [comment]
Same, haven't found any fixes for it either :(

**Comment by gihanmu** [comment]
Gets this issue on Windows 10

**Comment by Lilith1410** [comment]
Still pesists for me :/ ubuntu 18.04

**Comment by modianar** [comment]
From the windos command line (i.e. the gitbash command line) it didn't work for me (Windows 7). But it worked from the truffle develop command line
truffle develop
truffle(develop)> test
or
truffle(develop)> test ./test/Assert.sol
truffle(develop)> test ./test/DeployedAddresses.sol
